const actionTypes = {
  CREATE_PRODUCT_LOADING: 'CREATE_PRODUCT_LOADING',
  CREATE_PRODUCT_FAILURE: 'CREATE_PRODUCT_FAILURE',
  CREATE_PRODUCT_SUCCESS: 'CREATE_PRODUCT_SUCCESS'
};
export default actionTypes;
