const actionTypes = {
  CREATE_PRODUCT_LOADING: 'CREATE_PRODUCT_LOADING',
  CREATE_PRODUCT_FAILURE: 'CREATE_PRODUCT_FAILURE',
  CREATE_PRODUCT_SUCCESS: 'CREATE_PRODUCT_SUCCESS',
  GET_ALL_PRODUCTS_SUCCESS: 'GET_ALL_PRODUCTS_SUCCESS',
  GET_ALL_PRODUCTS_FAILURE: 'GET_ALL_PRODUCTS_FAILURE'
};
export default actionTypes;
